baseURL = 'https://imadrian.fyi/'
languageCode = 'en-us'
title = "I'm Adrian, FYI"
theme = "better-default"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    lineNos = true
    style = 'gruvbox'
    # style = 'native'
    # style = 'xcode-dark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true
